default:
  suites:
    menaiset:
      paths:
        - '%paths.base%/tests/features'
      filters:
        tags: '@menaiset'
      contexts:
        - FeatureContext:
            parameters:
              base_url: 'http://local.menaiset.fi'
        - DrupalContext
        - Drupal\DrupalExtension\Context\DrupalContext
        - Drupal\DrupalExtension\Context\MinkContext
        - Drupal\DrupalExtension\Context\MessageContext
        - Drupal\DrupalExtension\Context\DrushContext
        - IntegratedExperts\BehatScreenshotExtension\Context\ScreenshotContext
      extensions:
        Drupal\DrupalExtension:
          drupal:
            # This assumes that we're running Behat from within
            drupal_root: '/vagrant/drupal/current'

develop:
  suites:
    menaiset:
      paths:
        - '%paths.base%/tests/features'
      filters:
        tags: '@menaiset'
      contexts:
        - FeatureContext:
            parameters:
              base_url: 'https://sanomalifestyle:kanapalat@dev-menaiset.smf.aws.sanomacloud.net'
        - DrupalContext
        - Drupal\DrupalExtension\Context\DrupalContext
        - Drupal\DrupalExtension\Context\MinkContext
        - Drupal\DrupalExtension\Context\MessageContext
        - Drupal\DrupalExtension\Context\DrushContext
        - IntegratedExperts\BehatScreenshotExtension\Context\ScreenshotContext
      extensions:
        Drupal\DrupalExtension:
          drupal:
            # This assumes that we're running Behat from within
            drupal_root: '/vagrant/drupal/current'

staging:
  suites:
    menaiset:
      paths:
        - '%paths.base%/tests/features'
      filters:
        tags: '@menaiset'
      contexts:
        - FeatureContext:
            parameters:
              base_url: 'https://sanomalifestyle:kanapalat@staging-menaiset.smf.aws.sanomacloud.net'
        - DrupalContext
        - Drupal\DrupalExtension\Context\DrupalContext
        - Drupal\DrupalExtension\Context\MinkContext
        - Drupal\DrupalExtension\Context\MessageContext
        - Drupal\DrupalExtension\Context\DrushContext
        - IntegratedExperts\BehatScreenshotExtension\Context\ScreenshotContext
      extensions:
        Drupal\DrupalExtension:
          drupal:
            # This assumes that we're running Behat from within
            drupal_root: '/vagrant/drupal/current'

production:
  suites:
    menaiset:
      paths:
        - '%paths.base%/tests/features'
      filters:
        tags: '@menaiset'
      contexts:
        - FeatureContext:
            parameters:
              base_url: 'https://www.menaiset.fi'
        - DrupalContext
        - Drupal\DrupalExtension\Context\DrupalContext
        - Drupal\DrupalExtension\Context\MinkContext
        - Drupal\DrupalExtension\Context\MessageContext
        - Drupal\DrupalExtension\Context\DrushContext
        - IntegratedExperts\BehatScreenshotExtension\Context\ScreenshotContext
      extensions:
        Drupal\DrupalExtension:
          drupal:
            # This assumes that we're running Behat from within
            drupal_root: '/vagrant/drupal/current'

