default:
  suites:
    soppa365:
      paths:
        - '%paths.base%/tests/features'
      filters:
        tags: '@soppa365'
      contexts:
        - FeatureContext:
            parameters:
              base_url: 'http://local.soppa365.fi'
        - DrupalContext
        - Drupal\DrupalExtension\Context\DrupalContext
        - Drupal\DrupalExtension\Context\MinkContext
        - Drupal\DrupalExtension\Context\MessageContext
        - Drupal\DrupalExtension\Context\DrushContext
        - IntegratedExperts\BehatScreenshotExtension\Context\ScreenshotContext
      extensions:
        Drupal\DrupalExtension:
          drupal:
            # This assumes that we're running Behat from within
            drupal_root: '/vagrant/drupal/current'

develop:
  suites:
    soppa365:
      paths:
        - '%paths.base%/tests/features'
      filters:
        tags: '@soppa365'
      contexts:
        - FeatureContext:
            parameters:
              base_url: 'https://sanomalifestyle:kanapalat@dev-soppa365.smf.aws.sanomacloud.net'
        - DrupalContext
        - Drupal\DrupalExtension\Context\DrupalContext
        - Drupal\DrupalExtension\Context\MinkContext
        - Drupal\DrupalExtension\Context\MessageContext
        - Drupal\DrupalExtension\Context\DrushContext
        - IntegratedExperts\BehatScreenshotExtension\Context\ScreenshotContext
      extensions:
        Drupal\DrupalExtension:
          drupal:
            # This assumes that we're running Behat from within
            drupal_root: '/vagrant/drupal/current'

staging:
  suites:
    soppa365:
      paths:
        - '%paths.base%/tests/features'
      filters:
        tags: '@soppa365'
      contexts:
        - FeatureContext:
            parameters:
              base_url: 'https://sanomalifestyle:kanapalat@staging-soppa365.smf.aws.sanomacloud.net'
        - DrupalContext
        - Drupal\DrupalExtension\Context\DrupalContext
        - Drupal\DrupalExtension\Context\MinkContext
        - Drupal\DrupalExtension\Context\MessageContext
        - Drupal\DrupalExtension\Context\DrushContext
        - IntegratedExperts\BehatScreenshotExtension\Context\ScreenshotContext
      extensions:
        Drupal\DrupalExtension:
          drupal:
            # This assumes that we're running Behat from within
            drupal_root: '/vagrant/drupal/current'

production:
  suites:
    soppa365:
      paths:
        - '%paths.base%/tests/features'
      filters:
        tags: '@soppa365'
      contexts:
        - FeatureContext:
            parameters:
              base_url: 'https://www.soppa365.fi'
        - DrupalContext
        - Drupal\DrupalExtension\Context\DrupalContext
        - Drupal\DrupalExtension\Context\MinkContext
        - Drupal\DrupalExtension\Context\MessageContext
        - Drupal\DrupalExtension\Context\DrushContext
        - IntegratedExperts\BehatScreenshotExtension\Context\ScreenshotContext
      extensions:
        Drupal\DrupalExtension:
          drupal:
            # This assumes that we're running Behat from within
            drupal_root: '/vagrant/drupal/current'
